# Generated by Django 2.2.4 on 2019-08-24 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.IntegerField()),
                ('password', models.CharField(max_length=20)),
                ('sex', models.IntegerField()),
                ('head', models.CharField(max_length=500)),
                ('nickname', models.CharField(max_length=10)),
                ('posts', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Users',
                'managed': True,
            },
        ),
    ]
